# Site settings
title: quannt's personal blog
description: > # this means to ignore newlines until "baseurl:"
  This is quannt's personal blog. The view on this blog is solely from my personal point of view and does not represent my employer's.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: quannt91
github_username:  quannt

# Build settings
markdown: kramdown
source:      D:\Work\Blog\jekyll
destination: D:\Work\Blog\jekyll-staging
