

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Quannt | Programming Blog

description: c#, asp.net, javascript and more
author:
  name: quannt
  email: #
  github: quannt
  twitter: quannt91
  pinterest: 
  linkedin: 
  bio: 
  email_md5: 28410ec97da16f250a154d9b335c8a32
  disqus: quannt


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
